Improved error logging
Summary:
Current logging, should an error occur during e.g. client creation looks like following:
```
kuttl: harness.go:343: fatal error getting client
kuttl: harness.go:399: collecting cluster logs to artifacts/kind-logs-1589388270
kuttl: harness.go:443: tearing down kind cluster
kuttl: harness.go:465: Error response from daemon: reference does not exist
```
Here, the context `fatal error getting client` is separated from the actual error `Error response from daemon: reference does not exist` by multiple other lines, making it harder to read. This PR improves this by logging both together.

Signed-off-by: Aleksey Dukhovniy <alex.dukhovniy@googlemail.com>